name: flutter_spv
description: BIP 157/158 SPV Wallet 
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  core:
    path: core

flutter:
  uses-material-design: true

dev_dependencies:
  flutter_lints: ^5.0.0
  lints: ^5.1.1
  test: ^1.25.15