name: core
description: Core bitcoin wallet library
version: 1.0.0
environment:
  sdk: ^3.7.0

dependencies:
  crypto: ^3.0.6
  collection: ^1.19.1
  logger: ^2.5.0
  path: ^1.9.1
  sqflite: ^2.4.2

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15